# Jeffrey P2 - Prometheus Config V2
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'jeffrey-p2'
    environment: 'development'

# Scrape configs (sans Grafana metrics - Correction #4)
scrape_configs:
  # Prometheus self
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # NATS via exporter (service names)
  - job_name: 'nats'
    static_configs:
      - targets: ['nats-exporter:7777']
    scrape_interval: 10s

  # Redis via exporter (service names)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s

  # PostgreSQL via exporter (service names)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Note: Grafana metrics endpoint désactivé
  # Note: Caddy n'expose pas de metrics par défaut
