name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build services
        run: |
          docker-compose build

      - name: Start services
        run: |
          docker-compose up -d
          sleep 30  # Wait for services to be ready

      - name: Check services health
        run: |
          docker-compose ps
          docker-compose exec -T jeffrey-api curl -fsS http://localhost:8000/healthz

      - name: Run tests
        run: |
          docker-compose exec -T jeffrey-api pytest tests/ -v --tb=short

      - name: Check Alembic status (GPT safety fix)
        run: |
          docker-compose exec -T jeffrey-api bash -c 'cd /app && PYTHONPATH=/app/src alembic current'
          docker-compose exec -T jeffrey-api bash -c 'cd /app && PYTHONPATH=/app/src alembic history --verbose | tail -n 20'

      - name: Alembic dry-run validation
        run: |
          docker-compose exec -T jeffrey-api bash -c 'cd /app && PYTHONPATH=/app/src alembic upgrade head --sql | head -n 50'

      - name: Collect metrics
        run: |
          curl -s http://localhost:8000/metrics | grep -c jeffrey_ || true

      - name: Stop services
        if: always()
        run: docker-compose down

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy security scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'